# Generated by Django 3.2.18 on 2023-03-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travlo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
